### ISSUE TITLE
falsche Menüpunkt-Anzeige

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/geolocation#121]
**Description / Beschreibung**
Obwohl in den Benutzer- und Rollen-Einstellungen das Recht dafür nicht gegeben ist, bekommt der User trotzdem den Menüpunkt von Geolocation angezeigt, was dann bei Klick zu einer Fehlerseite führt, weil ja das Recht dafür nicht vergeben ist...

Workaround für mich wäre ähnlich wie beim bekannten yForm-Bug, das Ganze einfach via boot.php und EP manuell abzuschalten:

```  ### Menüpunkt "yForm" für Redakteure ausblenden
  if ((rex::isBackend()) && rex::getUser() && (!rex::getUser()->isAdmin())) {
    rex_extension::register('PAGES_PREPARED', function (rex_extension_point $ep) {
      $page = rex_be_controller::getPageObject('yform');
      $page->setHidden(true);
    });
  }
```

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.2
PHP: 8.1.13
Database: MariaDB 10.5.18
Browser: egal
AddOns: egal

**Did it whoops? / Whoops erhalten?**
Nein
<img width="263" alt="Bildschirmfoto 2023-01-05 um 16 47 35" src="https://user-images.githubusercontent.com/10958385/210831809-2e39eaef-4959-448f-8f8a-9c7344ed779c.png">

**Comment by christophboecker** [comment]
Danke für den Hinweis, Stefan.

Das Thema kommt mir aber bekannt vor; es war #111 und wurde gelöst durch eine zusätzliche Berechtigung `Geolocation[]`. Wenn man die auch abwählt ist der Menüpunkt ebenfalls weg. Das kommt aber erst im nächsten Release irgendwann diesen Monat raus.

Kannst Dir ja mal in der Zwischenzeit das aktuelle Repo ziehen und testen. Aber Vorsicht: es gibt BCs. 

Oder lokal den PR #112 einfügen: eine zusätzliche Zeile in der package.yml.

(ich mach dann mal hier zu)
