### ISSUE TITLE
Argument #2 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/geolocation#125]
Feedback eines Beta-Testers:
Ich habe soeben die 2.0beta installiert (neuestes Redaxo auf PHP 8.0) und ohne das ich großartig etwas an der nackten Installation verändert habe erhalte ich im Register "Kartensatz" beim Speichern des Datensatzes eine Fehlermeldung => siehe Screenshot.

<img width="1282" alt="Bildschirmfoto 2023-01-26 um 11 51 39" src="https://user-images.githubusercontent.com/10958385/214818390-16b7bd43-5d85-43a9-b544-24b4b57e6b0a.png">

Gruß,
Stefan

**Comment by dpf-dd** [comment]
Zur Vollständigkeit hier noch der letzte Eintrag vom Tracestack:
<img width="765" alt="Bildschirmfoto 2023-01-26 um 11 57 39" src="https://user-images.githubusercontent.com/10958385/214819416-6910ae2d-da35-4a2c-9a23-afaca94dee0f.png">

**Comment by christophboecker** [comment]
@dpf-dd war das eine Neuinstallation oder über ein Update?

**Comment by christophboecker** [comment]
Ah, ok, Ich hab mal ein System frisch aufgezogen und kriege den Fehler reproduziert. Damit kann ich arbeiten. Danke, ich schau mal

**Comment by christophboecker** [comment]
@dpf-dd Stefan, könntest Du mal testen und in `lib/yform/value/layerselect.php` die zwei Zeilen 94 und 95 ändern?

```php
$selectedLayers = isset($value['choice']) ? $value['choice'] : [];
$value = isset($value['value']) ? $value['value'] : [];
```

Bei mir läuft es mit der Änderung durch. Wenn bei Dir auch, mache ich nen PR dazu auf.

**Comment by christophboecker** [comment]
Danke fürs finden und testen.

**Comment by dpf-dd** [comment]
Danke für die schnelle Reaktion und Lösung. So macht das Spaß :)
