### ISSUE TITLE
**TypeError:** Cannot access offset of type string on string

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/geolocation#130]
**TypeError:** Cannot access offset of type string on string
**File:** redaxo/src/addons/yform/plugins/manager/fragments/yform/manager/page/list.php
**Line:** 152

in Verbindung mit yForm 4.0.4

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                                            | Line     |
| -------------------------------------------- | ------------------------------------------------------------------------------- | -------- |
| require                                      | redaxo/src/core/lib/fragment.php                                                | 119      |
| rex_fragment->{closure}                      | redaxo/src/core/lib/util/timer.php                                              | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/fragment.php                                                | 122      |
| rex_fragment->parse                          | redaxo/src/addons/yform/plugins/manager/fragments/yform/manager/page/layout.php | 20       |
| require                                      | redaxo/src/core/lib/fragment.php                                                | 119      |
| rex_fragment->{closure}                      | redaxo/src/core/lib/util/timer.php                                              | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/fragment.php                                                | 122      |
| rex_fragment->parse                          | redaxo/src/addons/yform/plugins/manager/lib/yform/manager/table.php             | 258      |
| rex_yform_manager_table->parseLayout         | redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php                   | 736      |
| rex_yform_manager->getDataPage               | redaxo/src/addons/yform/plugins/manager/pages/data_edit.php                     | 20       |
| include                                      | redaxo/src/addons/geolocation/pages/yform.php                                   | 58       |
| require                                      | redaxo/src/core/lib/packages/package.php                                        | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                                           | 503      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                                              | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                                           | 504      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                                           | 453      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/geolocation/pages/index.php                                   | 83       |
| require                                      | redaxo/src/core/lib/packages/package.php                                        | 233      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                                           | 503      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php                                              | 56       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php                                           | 504      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                                           | 436      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                                                     | 241      |
| require                                      | redaxo/src/core/boot.php                                                        | 155      |
| require                                      | redaxo/index.php                                                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.0, PHP 8.1.16, MariaDB 10.6.12)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.1.16     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MariaDB 10.6.12                |
| Character set | utf8mb4                        |
|       Warning | Die verwendete MariaDB-Version 10.6.12 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/16.3 |
|      Protocol | HTTP/1.0    |
|         HTTPS | yes         |

| Packages            |             |
| ------------------: | :---------- |
|             adminer | 1.9.3       |
|       animatedlogin | 1.0.0       |
|              backup | 2.9.0       |
|            be_style | 3.2.0       |
| be_style/customizer | 3.2.0       |
|     be_style/redaxo | 3.2.0       |
|             bloecks | 3.1.1       |
|    bloecks/cutncopy | 3.1.1       |
|   bloecks/dragndrop | 3.1.1       |
|                cke5 | 5.2.0       |
|             collect | 0.0.7-dev   |
|         collect/rss | 0.0.1-dev   |
|       collect/vimeo | 0.0.1-dev   |
|             cronjob | 2.10.0      |
|               debug | 1.3.0       |
|       fa_iconpicker | 1.2.0       |
|               feeds | 4.0.1       |
|           flatpickr | 1.1.1       |
|          focuspoint | 4.0.3       |
|           for_sa11y | 0.1.0       |
|              forcal | 3.7.3       |
|         geolocation | 2.0.0-beta2 |
|     global_settings | 2.8.4       |
|            icecoder | 3.0.1       |
|             install | 2.11.0      |
|         maintenance | 2.9.1       |
|              mblock | 3.4.11      |
|       media_manager | 2.14.0      |
|    media_negotiator | 2.0.0       |
|           mediapool | 2.13.0      |
|            metainfo | 2.10.0      |
|               mform | 7.2.7       |
|          mform/docs | 1.1         |
|             minibar | 2.3.1       |
|    navigation_array | 1.2.1       |
|           phpmailer | 2.12.0      |
|                plyr | 3.20.5      |
|             project | 0.0.1       |
|    quick_navigation | 6.0.2       |
|               sprog | 1.5.1       |
|          statistics | 2.4.0       |
|           structure | 2.15.0      |
|   structure/content | 2.15.0      |
|          theme_lock | 1.0.0       |
|    uikit_collection | 3.2.1       |
|            uploader | 2.3.0       |
|                 url | 2.1.0       |
|               users | 2.10.0      |
|              watson | 2.3.0       |
|               yform | 4.0.4       |
|         yform/email | 4.0.4       |
|       yform/manager | 4.0.4       |
|       yform_geo_osm | 1.2.8       |
|     yform_mediafile | 1.0.1'      |
|            yrewrite | 2.9.1       |
|     yrewrite_scheme | 3.6.2       |
|         zip_install | 1.2         |

</details>

**Comment by christophboecker** [comment]
Was genau hast Du denn da aufgerufen?

**Comment by skerbis** [comment]
Die Seiten von Geolocation. Vielleicht liegt's auch irgendwie an meinem System. Andere scheinen ja bislang nichts dergleichen gemeldet zu haben. Egal welchen Reiter des AddOns ich aufrufe wo eine YForm-Tabelle drin ist, passiert es.

**Comment by christophboecker** [comment]
Bei mir passiert es nicht. Sowohl die Listen (Mapset, Layer) als auch einzelne Formulare zu den Listeneinträgen laufen klaglos durch. R5.15.0, YForm 4.0.4.

DB-Thema? Ich habe MYSQL.

**Comment by skerbis** [comment]
Bei mir MariaDB. Der "normale" Tabellenaufruf funktioniert. Nur wenn diese als Seiten eingebunden sind, passiert es.

**Comment by skerbis** [comment]
@christophboecker ich bin schon etwas schlauer. 
Tatsächlich its es nicht das aktuelle YForm Release sondern wg. der Klon-Funktion die aktuelle Github-Version. (Sorry my fault) 

Dort knallt es hier: 

https://github.com/FriendsOfREDAXO/geolocation/blob/b8c1d0a9d4deb216f90b75e7f77f4b0a3f32f291/pages/index.php#L74-L80

**Comment by christophboecker** [comment]
Sieht irgendwie doppelt aus. Was passiert, wenn Du eine der beiden Zeilen 74 bzw. 77 auskommentierst?

**Comment by skerbis** [comment]
Danke lieber @christophboecker. yform_adminer habe ich nicht installiert. Aber sicher, es liegt an der Dev-Version von YForm. Ich denke ich habe die installiert, weil ich das neue klonen gerne einsetzen wollte.

**Comment by christophboecker** [comment]
@skerbis Hallo Thomas, kannst gerne mal testen, ob die aktuelle Version in Repo auch bei Dir mit mit dem GitHub-YForm läuft.

**Comment by skerbis** [comment]
Rockt 👍🏻
