### ISSUE TITLE
CURL Proxy-Aufruf ermöglichen 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/geolocation#132]
https://github.com/FriendsOfREDAXO/geolocation/pull/129

**Comment by christophboecker** [comment]
Wie gesagt: verstehe nichts von rex_socket aber so rein struturell gedacht:

- Tile-Abruf aus test_api.ph und layer.php entfernen und in eine "Service_Request.php" auslagern. Darin eine auf rex_socket basierende Klasse, die eher allgemeingültig arbeitet.
- Evtl per Factory-Trait überschreibbar (analog zu rex_sql, rex_list etc. mit einer für die eigene Umgebung abgepassten Version
- Darüber könten man perspecktivisch auch weitere Services realisieren (z.B. Geocoding und Reverse-Geocoding).

#28

**Comment by skerbis** [comment]
Ist aktuell mehr oder weniger eine Notiz. Wenn wir rex_socket nutzen müssen wir uns nicht mir Curl rumärgern.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/geolocation/releases/tag/2.0.0-beta3
