### ISSUE TITLE
Kompatibilität mit YForm 4.2 - Layer-Auswahl im Mapset

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/geolocation#157]
Im Formular für den Mapset sind zwei Felder (`...geolocation_layerselect extends ... be_manager_relation`), die das vom Erbonkel `rex_yform_value_be_manager_relation` erzeugte HTML (ein Widget) etwas umbauen. Grund: die darin befindlichten SELECT-OPTIONS dürfen um HTML-konform zu sein kein komplexes HTML enthalten. Das Select wird daher durch eine List-group ersetzt.

Seit YForm 4.2 klappt das nicht mehr, denn der Widget-Aufbau wurde geändert. 

Lösung ist in Arbeit. Geplant: `rex_yform_geolocation_layerselect` baut das HTML komplett selbst auf und basiert nicht mehr auf be_manager_relation.

**Comment by christophboecker** [comment]
@skerbis Hi, Thomas, ich hab in Branch "widget" ne geänderte Fassung. Sieht äußerlich identisch aus. Das betroffene Value "geolocation_layer" baut sein HTML jetzt komplett selbst, nutzt aber weiterhin die Ablauflogik aus be_manager_relation, um das Popup-Fenster zur Layer-Auswahl zu öffnen und die Auswahl zu übernehmen. YFragment und JS berücksichtigen die alte YForm-Widget-Struktur (identifizierende Tags und IDs) und die seit 4.2 neue Struktur. Mindestvoraussetzung ist also weiterhin YForm 4.0

Ich denke, dass dafür kein Major-Release nötig ist, da vergleichbares HTML erzeugt wird. Die neue Geolocation-Version wäre dann 2.3.0. Entscheidung liegt bei Dir als Addon-Lead.

**Comment by skerbis** [comment]
Alles klar, danke. Schaue ich mir an. - Ich werde mich auch wieder mehr hier kümmern. Versprochen.
