### ISSUE TITLE
Neue Karte anlegen/duplizieren: Transaktion wurde wegen folgendem Fehler nicht ausgeführt ...

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/geolocation#161]
Bei einem Kunden kam es zu folgendem Problem:

Beim Anlegen einer neuen Karte oder beim Duplizieren einer vorhandenen Karte gab es folgende Dauerfehlermeldung:

Transaktion wurde wegen folgendem Fehler nicht ausgeführt: count(): Argument #1 ($value) must be of type Countable|array, null given

Eine Fehleingabe kann fast ausgeschlossen werden, da der Fehler auch beim Duplizieren ausgegeben wurde.

Auch beim Duplizieren über yform kam diese Fehlermeldung.

Also habe ich die Validierungen geprüft.

In Layer::verifyLang war $value dann auch einmal null.

Ich habe dann in der Zeile 341 folgendes ergänzt:

$value = $value ?: [];

Was den Fehler behoben hat.

Ob diese Erkenntnis nun bahnbrechend ist, etwas davon in den Code einfließt oder nicht und vor allem in welcher Form will ich nicht entscheiden. Daher geht das hier als Issue raus und nicht als PR.

**Description / Beschreibung**

**Affected versions / Verwendete Versionen**

REDAXO: 5.17.1
PHP: 8.1 und 8.2
Database:
Browser: Firefox
System: laragon + gn2
AddOns:

**Did it whoops? / Whoops erhalten?**

Kein Whoops.

**Comment by christophboecker** [comment]
Danke für den Hinweis. Warum hab ich das bisher übersehen? Wenn man ein Formular hat, in dem das Sprachfeld leer ist, wird `null` an `verifyLang` übergeben und nicht `''`. Grade beim Klonen hätte ich das nicht erwartet, denn ohne gültigen Spracheintrag dürfte der Satz ja eh nicht gespeichert worden sein. Egal, Problem ist wie von Dir beschrieben gelöst. Danke.
