### ISSUE TITLE
Info Reiter findet Readme nicht

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/geolocation#24]
<img width="1191" alt="Bildschirmfoto 2022-02-07 um 14 47 46" src="https://user-images.githubusercontent.com/791247/152800113-bde68c5e-33b4-4b4a-9608-2ce8872d3b64.png">

**Comment by christophboecker** [comment]
Könntest Du mal schauen, was da hakt, bitte. Bei - Überraschung - mir klappt es nämlich.

Das alles passiert in der help.php. Ziemlich am Ende steht
```php
if( $path = $publish->getFilePath() ) {
} else {
   Fehlermeldung
}
```
Hier kommt kein valides Ergebnis und deshalb die Fehlermeldung. 
```php
function getFilePath()
{
    return $this->targetfile ? $this->dir . $this->targetfile : false;
}
```
Einfach mal $this bzw. unten $publish dumpen, was da drinsteht. Ansonsten: die Hauptarbeit passiert in __construct und getDocumentName.

**Comment by christophboecker** [comment]
@skerbis Hat sich da noch was ergeben, Thomas?

**Comment by skerbis** [comment]
Schaue ich gleich.

**Comment by skerbis** [comment]
@christophboecker ich frage mich gerade wo getFilePath her kommt?

**Comment by christophboecker** [comment]
Der steht hier:
https://github.com/FriendsOfREDAXO/geolocation/blob/f2bc1352404ffd2b96af07191583657cea589fc5/help.php#L178-L181
Aufruf hier:
https://github.com/FriendsOfREDAXO/geolocation/blob/f2bc1352404ffd2b96af07191583657cea589fc5/help.php#L425-L454

**Comment by skerbis** [comment]
Ergebnis ist bei der Readme immer ein false

**Comment by skerbis** [comment]
^ help_documentation {[#560 ▼]()
    +navigation: array:6 [[▶]()]
    +initialPage: ""
    +activePage: "docs/mapset.md"
    +dir: "/var/www/vhosts/git.mycms.dev/httpdocs/redaxo/src/addons/geolocation/"
    +dirLen: 69
    +filename: "readme.md"
    +filetype: "md"
    +targetfile: false
    +context: rex_addon {[#51 ▶]()}
    +prohibited: []
}

**Comment by christophboecker** [comment]
targetfile wird hier in der letzten Zeile des Constructors gesetzt:
https://github.com/FriendsOfREDAXO/geolocation/blob/f2bc1352404ffd2b96af07191583657cea589fc5/help.php#L118
und getDocumentName braucht die Vorleistungen aus dem Constructor. Irgendwo ist etwas auf Deinem System anders als bei mir.

**Comment by skerbis** [comment]
ich habe dieses REPO hier geladen . 
PHP Version ist 8.0.15

**Comment by christophboecker** [comment]
Ich teste morgen mal mit nem 8er PHP, bin z. Zt auf 7.4.

**Comment by skerbis** [comment]
brauchst nicht, gerade unter 7.4 getestet. Das selbe Problem

**Comment by skerbis** [comment]
BOAH BIN ICH BLIND. 
README.md wird groß geschrieben 
in der [help.yml](https://github.com/FriendsOfREDAXO/geolocation/blob/master/help.yml) wird es klein geschrieben 
https://github.com/FriendsOfREDAXO/geolocation/blob/f2bc1352404ffd2b96af07191583657cea589fc5/help.yml#L15

und folglich nicht gefunden :-) 
Du entwickelst unter Windows - oder?

**Comment by christophboecker** [comment]
> Du entwickelst unter Windows - oder?

macOS

ich mach morgen nen PR. Da muss man mal drauf kommen. Mercie

**Comment by skerbis** [comment]
Schon korrigiert.
