### ISSUE TITLE
UUID statt id

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/geolocation#33]
Nur mal so als Idee. Karten und Mapsets in den URLs nicht über die Datensatz-ID referenzieren, sondern über eine UUID. 

Technisch ist das kein großes Ding. Beim Update das neue UUID-Feld hinzufügen und fehlende UUID-Einträge erzeugen. Die Nutzung sollte eh über generierten Code erfolgen. Nur wer die Proxy-Urls von Hand fest in sein JS gebaut hat, muss etwas umbasteln.

Vieleicht könnte man auf die Art auch mal einen Pool an Karten- und Service-URLs aufbauen, die bei jedem Update automatisch ausgeliefert und mit eingespielt werden.

**Comment by skerbis** [comment]
Karten- und Service-URLs: Darüber habe ich auch nachgedacht. Leider ist es so, dass einige Tile-Anbieter ständig ihre Nutzungsbedingungen ändern. Ich wäre daher vorsichtig hier einen Pool zur Verfügung zu stellen. Besser ist es z.B. auf die Website https://wiki.openstreetmap.org/wiki/Tile_servers zu verweisen und auf die Nutzungsbedingungen hinzuweisen.

**Comment by christophboecker** [comment]
Mal abgesehen von der Pool-Idee ... was ist denn Deine Meinung zur Frage UUID oder id? Jetzt ließe es sich noch ohne BC einbauen.

**Comment by skerbis** [comment]
Ich bin eher ein Freund von eindeutigen keys je Url denn für UUID. Finde keys freundlicher und intuitiver.

**Comment by christophboecker** [comment]
Na ja, ich finde das Konzept der UUID grundsätzlich nicht schlecht. Sind natürlich viel länger. Ich stampfe die Idee dann mal ein. Hab grade eh keine Lust, da was zu programmieren.

**Comment by skerbis** [comment]
Ich wollte es dir nicht schlechteren :-(

**Comment by christophboecker** [comment]
Na ja, ich hatte den Artikel in der c´t dazu gelesen und finde das Thema generell spannend. Aber ... für Geolocation bist nun DU der Produktmanager. :-)
