### ISSUE TITLE
PHP Libs sollten per Composer aktualisiert werden

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/geolocation#37]
https://github.com/FriendsOfREDAXO/geolocation/pull/36

**Comment by christophboecker** [comment]
Kann man dem Composer nicht irgendwie beibiegen,das Notwendige zu holen und nicht diesen elenden Streuschuß zu machen. Und warum muss sich der Composer in jedem Addon noch mal einnisten. Nicht meine Welt, ich bin zu alt für sowas. IBM 129 rocks :-)

**Comment by skerbis** [comment]
Die Compiler Field kannst du im Release aussperren

**Comment by christophboecker** [comment]
> Vorteil beim composer ist das leichte updaten

Da haben wir beide mit Sicherheit sehr unterschiedliche Voraussetzungen. Du mit einer Profi-Entwicklugsumgebung und ich mit meinem Hobby-Setup. Ich kann nur nen Repo aus Github in den lokalen Vendor-Folder herunterladen und später per Drag&Drop im Browser nach Github hochladen. Der Composer kommt in dem Workflow gar nicht vor. 

> Die Composrr Files kannst du im Release aussperren

Dan sollte man das tun. Und aus den Vendor-Repos auch gleich das ganze überflüssige Zeugs. Nur: wie?

**Comment by skerbis** [comment]
ich habe den PR angepasst. Damit ich weiter per composer updaten kann bitte an die Ordnerstruktur halten. Du kannst dort weiterhin das Release reinladen. Der Ordner sollte aber so bleiben.

**Comment by christophboecker** [comment]
Google Google und studier ... `.gitattributes` kann helfen hier :-)

Ich hab es mal in einer kleinen Testumgebung ausprobiert und es klappt tatsächlich, damit Dateien und Ordner aus dem Release auszuschließen. Man könnte also ganze Verzeichnisse ausblenden und auch die Teile aus phpgeo, die im Release nicht erforderlich sind (make-Dateien, Test, Doc, ..)

```
vendor/mjaschen/phpgeo/docs/ export-ignore
vendor/mjaschen/phpgeo/tests/ export-ignore
vendor/mjaschen/phpgeo/Makefile export-ignore
vendor/mjaschen/phpgeo/composer.json export-ignore
vendor/mjaschen/phpgeo/phive.xml export-ignore
vendor/mjaschen/phpgeo/phpcs.xml.dist export-ignore
vendor/mjaschen/phpgeo/phpdox.xml export-ignore
vendor/mjaschen/phpgeo/phpunit.xml export-ignore
vendor/mjaschen/phpgeo/psalm.xml  export-ignore
```
ich bau das mal ein.
