### ISSUE TITLE
Kleine Darkmode Anpassung (Legend)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/geolocation#42]
![image](https://user-images.githubusercontent.com/330516/160610026-50cf18f5-7032-4eec-9e9e-b2054c567cdd.png)

oder gehört das zu yform?

**Comment by christophboecker** [comment]
Jo, das kommt tatsächlich aus dem CSS für Geolocation.
https://github.com/FriendsOfREDAXO/geolocation/blob/c2593e6497bea112e2fbbd16ca23e040b369fc39/install/geolocation_be.css#L1-L6
 Ich fand die Fieldset-Label-Darstellung blöd. Und da ich kein Darkmode-Nutzer bin gibt es auch (noch) keine Darkmode-Ausweichlösung. 

@skerbis Das müssten wir noch vor dem 1.0.0-Release fixen.

**Comment by skerbis** [comment]
Ich nehme es erstmal raus. Für mich passen die default-Stile.
