### ISSUE TITLE
Nächstes Major-Release ab PHP 8.0? Oder 8.1

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/geolocation#64]
Nur mal so in den Raum gestellt und weil ich grade das Addon mit RexStan durchflöhe und dabei nur PHP 8.0 / 8.1 / 8.2 teste:

Was haltet ihr davon, das nächste (Major-)Release an PHP 8.0 zu koppeln. Oder gleich 8.1. Man muss ja mal anfangen ....

**Comment by schuer** [comment]
7.4 ist kurz vor obsolet, insofern fände ich 8 als Minimum voll okay.

**Comment by skerbis** [comment]
8.0  👍🏻

**Comment by christophboecker** [comment]
Na ja, für 8.0 endet der aktive Support in einem Monat. Ich bin für ein radikales 8.1

**Comment by christophboecker** [comment]
Ich mach mal zu. Die Beta ist ja unterwegs und auf PHP ^8 eingestellt.
