### ISSUE TITLE
HTML-Colorcodes für Marker-Farben escapen 

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/geolocation#69]
Hintergrund: es gibt im JS eine Funktion, die farbige Marker als Inline-SVG erzeugt. Der erzeugte Code ist escaped, also z.B. `"` ist durch `%22` ersetzt. Die an die Funktion übergebenen Farb**namen** (z.B. `green`) werden auch klaglos richtig in den Code eingesetzt. Mit Farb**codes** (z.B. `#008800') geht das schief.

Aktueller Workaround: Farbcodes als `%23....` (z.B. `%23008800`) selbst escapen.

Für die nächste Version das JS selbst escapen lassen.

**Comment by TobiasKrais** [comment]
Wenn du mir sagen kannst wo die Stelle im Code ist, programmiere ich einen PR.

**Comment by christophboecker** [comment]
Danke für das Angebot. Da ich ohnenhin grade eine großangelegte RexStan-getriggerte Überarbeitung mache, erledige ich das gleich mit. Es gibt jetzt erstmal eh kein Release. 

Wenn Du für Dich bis dahin die Sache fixen willst:
https://github.com/FriendsOfREDAXO/geolocation/blob/9b37e12b00f8fa4d40ecce5d3fea382da5c80b98/install/geolocation.js#L89-L93
Hier im Code einfach `color = encodeURI(color);` ergänzen.

Und danach einmal die Einstellungsseite speichern! Dann wird das gesamte CSS/JS neu in das Asset-Verzeichnis compiliert. Sollte jedenfalls ;-)

**Comment by TobiasKrais** [comment]
Hilft leider nicht. Die Raute bleibt.

**Comment by TobiasKrais** [comment]
Ich hab den Bugfix gerade getestet. Funktioniert bei mir leider nicht.

**Comment by christophboecker** [comment]
Danke für den Hinweis. Es musste `encodeURIComponent` sein und nicht `encodeURI`. #94

**Comment by TobiasKrais** [comment]
Getestet. Jetzt funktioniert es korrekt. Danke dir!
